# Makefile.in generated by automake 1.16.3 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2020 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# Top level Makefile for rpm






am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/rpm
pkgincludedir = $(includedir)/rpm
pkglibdir = $(libdir)/rpm
pkglibexecdir = $(libexecdir)/rpm
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-pc-linux-gnu
host_triplet = x86_64-pc-linux-gnu
#am__append_1 = db3
am__append_2 = luaext
am__append_3 = python
am__append_4 = plugins
am__append_5 = tests
bin_PROGRAMS = rpm$(EXEEXT) rpm2cpio$(EXEEXT) rpmbuild$(EXEEXT) \
	rpmdb$(EXEEXT) rpmkeys$(EXEEXT) rpmsign$(EXEEXT) \
	rpmspec$(EXEEXT) $(am__EXEEXT_1) rpmgraph$(EXEEXT)
am__append_6 = rpm2archive 
rpmlibexec_PROGRAMS = $(am__EXEEXT_2) $(am__EXEEXT_3) rpmdeps$(EXEEXT)
am__append_7 = scripts/find-debuginfo.sh
am__append_8 = debugedit
am__append_9 = -ldw
#am__append_10 = -ldw -lebl
am__append_11 = elfdeps sepdebugcrcfix
#am__append_12 = doc/hacking/html/index.html
am__append_13 = doc/librpm/html/index.html
#am__append_14 = db.h
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/gettext.m4 \
	$(top_srcdir)/m4/iconv.m4 $(top_srcdir)/m4/lib-ld.m4 \
	$(top_srcdir)/m4/lib-link.m4 $(top_srcdir)/m4/lib-prefix.m4 \
	$(top_srcdir)/m4/libtool.m4 $(top_srcdir)/m4/ltoptions.m4 \
	$(top_srcdir)/m4/ltsugar.m4 $(top_srcdir)/m4/ltversion.m4 \
	$(top_srcdir)/m4/lt~obsolete.m4 $(top_srcdir)/m4/nls.m4 \
	$(top_srcdir)/m4/po.m4 $(top_srcdir)/m4/progtest.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(dist_bin_SCRIPTS) \
	$(pkginclude_HEADERS) $(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__EXEEXT_1 = rpm2archive$(EXEEXT)
am__installdirs = "$(DESTDIR)$(bindir)" "$(DESTDIR)$(rpmlibexecdir)" \
	"$(DESTDIR)$(bindir)" "$(DESTDIR)$(rpmconfigdir)" \
	"$(DESTDIR)$(pkgconfigdir)" "$(DESTDIR)$(rpmconfigdir)" \
	"$(DESTDIR)$(rpmvardir)" "$(DESTDIR)$(pkgincludedir)" \
	"$(DESTDIR)$(pkgincludedir)"
am__EXEEXT_2 =  \
	debugedit$(EXEEXT)
am__EXEEXT_3 = elfdeps$(EXEEXT) sepdebugcrcfix$(EXEEXT)
PROGRAMS = $(bin_PROGRAMS) $(rpmlibexec_PROGRAMS)
LTLIBRARIES = $(noinst_LTLIBRARIES)
libcliutils_la_DEPENDENCIES = lib/librpm.la rpmio/librpmio.la
am_libcliutils_la_OBJECTS = libcliutils_la-cliutils.lo
libcliutils_la_OBJECTS = $(am_libcliutils_la_OBJECTS)
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
am__debugedit_SOURCES_DIST = tools/debugedit.c tools/hashtab.c \
	tools/hashtab.h
am__dirstamp = $(am__leading_dot)dirstamp
am_debugedit_OBJECTS = tools/debugedit.$(OBJEXT) \
	tools/hashtab.$(OBJEXT)
debugedit_OBJECTS = $(am_debugedit_OBJECTS)
am__DEPENDENCIES_1 =
debugedit_DEPENDENCIES =  \
	rpmio/librpmio.la \
	$(am__DEPENDENCIES_1) \
	$(am__DEPENDENCIES_1)
am__elfdeps_SOURCES_DIST = tools/elfdeps.c
am_elfdeps_OBJECTS = tools/elfdeps.$(OBJEXT)
elfdeps_OBJECTS = $(am_elfdeps_OBJECTS)
elfdeps_DEPENDENCIES = rpmio/librpmio.la lib/librpm.la
am_rpm_OBJECTS = rpm-rpmqv.$(OBJEXT)
rpm_OBJECTS = $(am_rpm_OBJECTS)
rpm_DEPENDENCIES = libcliutils.la lib/librpm.la rpmio/librpmio.la
am_rpm2archive_OBJECTS = rpm2archive.$(OBJEXT)
rpm2archive_OBJECTS = $(am_rpm2archive_OBJECTS)
rpm2archive_DEPENDENCIES = lib/librpm.la rpmio/librpmio.la
am_rpm2cpio_OBJECTS = rpm2cpio.$(OBJEXT)
rpm2cpio_OBJECTS = $(am_rpm2cpio_OBJECTS)
rpm2cpio_DEPENDENCIES = lib/librpm.la rpmio/librpmio.la
am_rpmbuild_OBJECTS = rpmbuild-rpmbuild.$(OBJEXT)
rpmbuild_OBJECTS = $(am_rpmbuild_OBJECTS)
rpmbuild_DEPENDENCIES = libcliutils.la build/librpmbuild.la \
	lib/librpm.la rpmio/librpmio.la
am_rpmdb_OBJECTS = rpmdb-rpmdb.$(OBJEXT)
rpmdb_OBJECTS = $(am_rpmdb_OBJECTS)
rpmdb_DEPENDENCIES = libcliutils.la lib/librpm.la rpmio/librpmio.la
am_rpmdeps_OBJECTS = tools/rpmdeps.$(OBJEXT)
rpmdeps_OBJECTS = $(am_rpmdeps_OBJECTS)
rpmdeps_DEPENDENCIES = lib/librpm.la rpmio/librpmio.la \
	build/librpmbuild.la
am_rpmgraph_OBJECTS = tools/rpmgraph.$(OBJEXT)
rpmgraph_OBJECTS = $(am_rpmgraph_OBJECTS)
rpmgraph_DEPENDENCIES = lib/librpm.la rpmio/librpmio.la
am_rpmkeys_OBJECTS = rpmkeys-rpmkeys.$(OBJEXT)
rpmkeys_OBJECTS = $(am_rpmkeys_OBJECTS)
rpmkeys_DEPENDENCIES = libcliutils.la lib/librpm.la rpmio/librpmio.la
am_rpmsign_OBJECTS = rpmsign-rpmsign.$(OBJEXT)
rpmsign_OBJECTS = $(am_rpmsign_OBJECTS)
rpmsign_DEPENDENCIES = libcliutils.la sign/librpmsign.la lib/librpm.la \
	rpmio/librpmio.la
am_rpmspec_OBJECTS = rpmspec-rpmspec.$(OBJEXT)
rpmspec_OBJECTS = $(am_rpmspec_OBJECTS)
rpmspec_DEPENDENCIES = libcliutils.la build/librpmbuild.la \
	lib/librpm.la rpmio/librpmio.la
am__sepdebugcrcfix_SOURCES_DIST = tools/sepdebugcrcfix.c
am_sepdebugcrcfix_OBJECTS =  \
	tools/sepdebugcrcfix.$(OBJEXT)
sepdebugcrcfix_OBJECTS = $(am_sepdebugcrcfix_OBJECTS)
sepdebugcrcfix_DEPENDENCIES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
SCRIPTS = $(dist_bin_SCRIPTS) $(rpmconfig_SCRIPTS)
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = 
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__maybe_remake_depfiles = depfiles
am__depfiles_remade = ./$(DEPDIR)/libcliutils_la-cliutils.Plo \
	./$(DEPDIR)/rpm-rpmqv.Po ./$(DEPDIR)/rpm2archive.Po \
	./$(DEPDIR)/rpm2cpio.Po ./$(DEPDIR)/rpmbuild-rpmbuild.Po \
	./$(DEPDIR)/rpmdb-rpmdb.Po ./$(DEPDIR)/rpmkeys-rpmkeys.Po \
	./$(DEPDIR)/rpmsign-rpmsign.Po ./$(DEPDIR)/rpmspec-rpmspec.Po \
	tools/$(DEPDIR)/debugedit.Po tools/$(DEPDIR)/elfdeps.Po \
	tools/$(DEPDIR)/hashtab.Po tools/$(DEPDIR)/rpmdeps.Po \
	tools/$(DEPDIR)/rpmgraph.Po tools/$(DEPDIR)/sepdebugcrcfix.Po
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
SOURCES = $(libcliutils_la_SOURCES) $(debugedit_SOURCES) \
	$(elfdeps_SOURCES) $(rpm_SOURCES) $(rpm2archive_SOURCES) \
	$(rpm2cpio_SOURCES) $(rpmbuild_SOURCES) $(rpmdb_SOURCES) \
	$(rpmdeps_SOURCES) $(rpmgraph_SOURCES) $(rpmkeys_SOURCES) \
	$(rpmsign_SOURCES) $(rpmspec_SOURCES) \
	$(sepdebugcrcfix_SOURCES)
DIST_SOURCES = $(libcliutils_la_SOURCES) $(am__debugedit_SOURCES_DIST) \
	$(am__elfdeps_SOURCES_DIST) $(rpm_SOURCES) \
	$(rpm2archive_SOURCES) $(rpm2cpio_SOURCES) $(rpmbuild_SOURCES) \
	$(rpmdb_SOURCES) $(rpmdeps_SOURCES) $(rpmgraph_SOURCES) \
	$(rpmkeys_SOURCES) $(rpmsign_SOURCES) $(rpmspec_SOURCES) \
	$(am__sepdebugcrcfix_SOURCES_DIST)
RECURSIVE_TARGETS = all-recursive check-recursive cscopelist-recursive \
	ctags-recursive dvi-recursive html-recursive info-recursive \
	install-data-recursive install-dvi-recursive \
	install-exec-recursive install-html-recursive \
	install-info-recursive install-pdf-recursive \
	install-ps-recursive install-recursive installcheck-recursive \
	installdirs-recursive pdf-recursive ps-recursive \
	tags-recursive uninstall-recursive
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
DATA = $(noinst_DATA) $(pkgconfig_DATA) $(rpmconfig_DATA) \
	$(rpmvar_DATA)
HEADERS = $(nodist_pkginclude_HEADERS) $(pkginclude_HEADERS)
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
am__recursive_targets = \
  $(RECURSIVE_TARGETS) \
  $(RECURSIVE_CLEAN_TARGETS) \
  $(am__extra_recursive_targets)
AM_RECURSIVE_TARGETS = $(am__recursive_targets:-recursive=) TAGS CTAGS \
	cscope distdir distdir-am dist dist-all distcheck
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP) \
	config.h.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
am__DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/config.h.in \
	$(top_srcdir)/preinstall.am $(top_srcdir)/rpm.am ABOUT-NLS \
	COPYING ChangeLog INSTALL README compile config.guess \
	config.rpath config.sub depcomp install-sh ltmain.sh missing \
	mkinstalldirs
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
am__relativize = \
  dir0=`pwd`; \
  sed_first='s,^\([^/]*\)/.*$$,\1,'; \
  sed_rest='s,^[^/]*/*,,'; \
  sed_last='s,^.*/\([^/]*\)$$,\1,'; \
  sed_butlast='s,/*[^/]*$$,,'; \
  while test -n "$$dir1"; do \
    first=`echo "$$dir1" | sed -e "$$sed_first"`; \
    if test "$$first" != "."; then \
      if test "$$first" = ".."; then \
        dir2=`echo "$$dir0" | sed -e "$$sed_last"`/"$$dir2"; \
        dir0=`echo "$$dir0" | sed -e "$$sed_butlast"`; \
      else \
        first2=`echo "$$dir2" | sed -e "$$sed_first"`; \
        if test "$$first2" = "$$first"; then \
          dir2=`echo "$$dir2" | sed -e "$$sed_rest"`; \
        else \
          dir2="../$$dir2"; \
        fi; \
        dir0="$$dir0"/"$$first"; \
      fi; \
    fi; \
    dir1=`echo "$$dir1" | sed -e "$$sed_rest"`; \
  done; \
  reldir="$$dir2"
DIST_ARCHIVES = $(distdir).tar.gz $(distdir).tar.bz2
GZIP_ENV = --best
DIST_TARGETS = dist-bzip2 dist-gzip
# Exists only to be overridden by the user if desired.
AM_DISTCHECK_DVI_TARGET = dvi
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} '/insilications/apps/rpm-4.14.2.1-1/missing' aclocal-1.16
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AR = /usr/bin/gcc-ar
AS = as
AUTOCONF = ${SHELL} '/insilications/apps/rpm-4.14.2.1-1/missing' autoconf
AUTOHEADER = ${SHELL} '/insilications/apps/rpm-4.14.2.1-1/missing' autoheader
AUTOM4TE = /usr/bin/autom4te
AUTOMAKE = ${SHELL} '/insilications/apps/rpm-4.14.2.1-1/missing' automake-1.16
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g3 -Og -march=native -mtune=native -fPIC -Wall -Wextra -fuse-ld=bfd -fuse-linker-plugin -pipe -ffat-lto-objects -pthread
CPP = gcc -E
CPPFLAGS =  -I/usr/include/nss3
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g3 -Og -march=native -mtune=native -fPIC -Wall -Wextra -fuse-ld=bfd -fuse-linker-plugin -pipe -ffat-lto-objects -pthread
CYGPATH_W = echo
DBUS_CFLAGS = 
DBUS_LIBS = 
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = false
DOXYGEN = /usr/bin/doxygen
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
FGREP = /usr/bin/grep -F
FIXPERMS = a+rX,u+w,g-w,o-w
GMSGFMT = /usr/bin/msgfmt
GMSGFMT_015 = /usr/bin/msgfmt
GREP = /usr/bin/grep
HAVE_BN2BINPAD = 
HAVE_DOT = YES
HAVE_DSA_SET0_KEY = 
HAVE_DSA_SET0_PQG = 
HAVE_DSA_SIG_SET0 = 
HAVE_EVP_MD_CTX_NEW = 
HAVE_NSS_INITCONTEXT = 1
HAVE_RSA_SET0_KEY = 
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
INTLLIBS = 
INTL_MACOSX_LIBS = 
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS = -g3 -Og -march=native -mtune=native -fPIC -Wall -Wextra -fuse-ld=bfd -fuse-linker-plugin -pipe -ffat-lto-objects -pthread -lpthread
LIBICONV = 
LIBINTL = 
LIBOBJS =  ${LIBOBJDIR}fnmatch$U.o
LIBS = -ldl -lpthread 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LMDB_CFLAGS = 
LMDB_LIBS = -llmdb
LMDB_REQUIRES = lmdb
LN_S = ln -s
LTLIBICONV = 
LTLIBINTL = 
LTLIBOBJS =  ${LIBOBJDIR}fnmatch$U.lo
LT_SYS_LIBRARY_PATH = 
LUA_CFLAGS = -I/usr/include/lua-5.3
LUA_LIBS = -llua5.3 -ldl -lm
MAKEINFO = ${SHELL} '/insilications/apps/rpm-4.14.2.1-1/missing' makeinfo
MANIFEST_TOOL = :
MKDIR_P = /usr/bin/mkdir -p
MSGFMT = /usr/bin/msgfmt
MSGFMT_015 = /usr/bin/msgfmt
MSGMERGE = /usr/bin/msgmerge
NM = /usr/bin/gcc-nm
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = rpm
PACKAGE_BUGREPORT = rpm-maint@lists.rpm.org
PACKAGE_NAME = rpm
PACKAGE_STRING = rpm 4.14.2.1
PACKAGE_TARNAME = rpm
PACKAGE_URL = 
PACKAGE_VERSION = 4.14.2.1
PATH_SEPARATOR = :
PKGCONFIG = /usr/bin/pkg-config
PKG_CONFIG = /usr/bin/pkg-config
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = 
POSUB = po
PYTHON = /usr/bin/python
PYTHON_CFLAGS = -I/usr/include/python3.9
PYTHON_EXEC_PREFIX = ${exec_prefix}
PYTHON_LIB = 
PYTHON_LIBS = 
PYTHON_PLATFORM = linux
PYTHON_PREFIX = ${prefix}
PYTHON_VERSION = 3.9
RANLIB = /usr/bin/gcc-ranlib
RPMCANONGNU = -gnu
RPMCANONOS = linux
RPMCANONVENDOR = pc
RPMCFLAGS = -fPIC -DPIC -D_REENTRANT -Wall -Wpointer-arith -Wmissing-prototypes -Wstrict-prototypes  -fno-strict-aliasing -fstack-protector -Wempty-body
RPMCONFIGDIR = /usr/lib/rpm
RUNDIR = /run
SED = /usr/bin/sed
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
USE_NLS = yes
VERSION = 4.14.2.1
WITH_ACL_LIB = -lacl
WITH_ARCHIVE_INCLUDE = 
WITH_ARCHIVE_LIB = -larchive
WITH_BEECRYPT_INCLUDE = 
WITH_BEECRYPT_LIB = 
WITH_BZ2_LIB = -lbz2
WITH_CAP_LIB = -lcap
WITH_DB_LIB = -ldb
WITH_IMAEVM_LIB = 
WITH_LIBDW_LIB = -ldw
WITH_LIBELF_LIB = -lelf
WITH_LZMA_LIB = -llzma
WITH_MAGIC_INCLUDE = 
WITH_MAGIC_LIB = -lmagic
WITH_NSS_INCLUDE = 
WITH_NSS_LIB = -lnss3
WITH_OPENSSL_INCLUDE = 
WITH_OPENSSL_LIB = 
WITH_POPT_INCLUDE = 
WITH_POPT_LIB = /usr/lib64/libpopt.a
WITH_SELINUX_LIB = 
WITH_SEMANAGE_LIB = 
WITH_ZLIB_INCLUDE = 
WITH_ZLIB_LIB = -lz
XGETTEXT = /usr/bin/xgettext
XGETTEXT_015 = /usr/bin/xgettext
YACC = bison -y
YFLAGS = 
ZSTD_CFLAGS = 
ZSTD_LIBS = -lzstd
ZSTD_REQUIRES = libzstd
__7ZIP = /usr/bin/7za
__BZIP2 = /usr/bin/bzip2
__BZR = /usr/bin/bzr
__CAT = /usr/bin/cat
__CC = gcc
__CHGRP = /usr/bin/chgrp
__CHMOD = /usr/bin/chmod
__CHOWN = /usr/bin/chown
__CP = /usr/bin/cp
__CPIO = /usr/bin/cpio
__CURL = /usr/bin/curl
__FAKECHROOT = /usr/bin/fakechroot
__FILE = /usr/bin/file
__GEM = /usr/bin/gem
__GIT = /usr/bin/haswell/git
__GPG = /usr/bin/gpg2
__GREP = /usr/bin/grep
__GZIP = /usr/bin/gzip
__HG = /usr/bin/hg
__ID = /usr/bin/id
__INSTALL = /usr/bin/install
__LD = /usr/bin/ld
__LRZIP = /usr/bin/lrzip
__LZIP = /usr/bin/lzip
__MAKE = /usr/bin/make
__MKDIR = /usr/bin/mkdir
__MKDIR_P = /usr/bin/mkdir -p
__MV = /usr/bin/mv
__NM = /usr/bin/nm
__OBJCOPY = /usr/bin/objcopy
__OBJDUMP = /usr/bin/objdump
__PATCH = /usr/bin/patch
__PERL = /usr/bin/perl
__PGP = /usr/bin/pgp
__PYTHON = /usr/bin/python
__QUILT = /usr/bin/quilt
__RESTORECON = /sbin/restorecon
__RM = /usr/bin/rm
__RSH = /usr/bin/rsh
__SED = /usr/bin/sed
__SEMODULE = /usr/bin/semodule
__SSH = /usr/bin/ssh
__STRIP = /usr/bin/strip
__TAR = /usr/bin/tar
__UNZIP = /usr/bin/unzip
__XZ = /usr/bin/xz
__ZSTD = /usr/bin/zstd
abs_builddir = /insilications/apps/rpm-4.14.2.1-1
abs_srcdir = /insilications/apps/rpm-4.14.2.1-1
abs_top_builddir = /insilications/apps/rpm-4.14.2.1-1
abs_top_srcdir = /insilications/apps/rpm-4.14.2.1-1
ac_ct_AR = /usr/bin/gcc-ar
ac_ct_CC = gcc
ac_ct_CXX = 
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = tar --format=posix -chf - "$$tardir"
am__untar = tar -xf -
bindir = ${exec_prefix}/bin
build = x86_64-pc-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
dirstamp = ${am__leading_dot}dirstamp
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-pc-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux
host_vendor = pc
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /insilications/apps/rpm-4.14.2.1-1/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /usr/bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
pkgpyexecdir = ${pyexecdir}/rpm
pkgpythondir = ${pythondir}/rpm
prefix = /usr
program_transform_name = s,x,x,
psdir = ${docdir}
pyexecdir = ${exec_prefix}/lib/python3.9/site-packages
pythondir = ${prefix}/lib/python3.9/site-packages
runstatedir = ${localstatedir}/run
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
subdirs = 
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
ACLOCAL_AMFLAGS = -I m4
DISTCHECK_CONFIGURE_FLAGS = --with-external-db --enable-python

# Internal binaries
rpmlibexecdir = $(prefix)/lib/rpm

# Host independent config files
rpmconfigdir = $(prefix)/lib/rpm

# Libtool version (current-revision-age) for all our libraries
rpm_version_info = 9:0:1
AM_CFLAGS = -fPIC -DPIC -D_REENTRANT -Wall -Wpointer-arith -Wmissing-prototypes -Wstrict-prototypes  -fno-strict-aliasing -fstack-protector -Wempty-body
CLEANFILES = rpmrc.tmp rpmrc macros platform.tmp platform rpm.pc.tmp \
	rpm.pc rpmpopt-4.14.2.1.tmp rpmpopt-4.14.2.1 \
	include/rpm/argv.h include/rpm/rpmio.h include/rpm/rpmurl.h \
	include/rpm/rpmmacro.h include/rpm/rpmlog.h \
	include/rpm/rpmpgp.h include/rpm/rpmsq.h \
	include/rpm/rpmstring.h include/rpm/rpmstrpool.h \
	include/rpm/rpmsw.h include/rpm/rpmfileutil.h \
	include/rpm/rpmutil.h include/rpm/rpmkeyring.h \
	include/rpm/rpmbase64.h include/rpm/header.h \
	include/rpm/rpmdb.h include/rpm/rpmcallback.h \
	include/rpm/rpmcli.h include/rpm/rpmlib.h include/rpm/rpmds.h \
	include/rpm/rpmfi.h include/rpm/rpmfiles.h \
	include/rpm/rpmpol.h include/rpm/rpmps.h include/rpm/rpmprob.h \
	include/rpm/rpmtag.h include/rpm/rpmtd.h include/rpm/rpmte.h \
	include/rpm/rpmts.h include/rpm/rpmtypes.h include/rpm/rpmvf.h \
	include/rpm/rpmarchive.h include/rpm/rpmsign.h \
	include/rpm/rpmbuild.h include/rpm/rpmfc.h \
	include/rpm/rpmspec.h

# Used for the testsuite to test creating debuginfo packages
EXTRA_DIST = ChangeLog CREDITS INSTALL autogen.sh db3/configure \
	installplatform platform.in rpmrc.in macros.in macros.debug \
	platform.in rpm.pc.in rpmpopt.in doc/hacking.doxy.in \
	doc/hacking/Doxyheader.h doc/librpm.doxy.in \
	doc/librpm/Doxyheader.h doc/librpm/html
BUILT_SOURCES = $(am__append_14) include/rpm/argv.h \
	include/rpm/rpmio.h include/rpm/rpmurl.h \
	include/rpm/rpmmacro.h include/rpm/rpmlog.h \
	include/rpm/rpmpgp.h include/rpm/rpmsq.h \
	include/rpm/rpmstring.h include/rpm/rpmstrpool.h \
	include/rpm/rpmsw.h include/rpm/rpmfileutil.h \
	include/rpm/rpmutil.h include/rpm/rpmkeyring.h \
	include/rpm/rpmbase64.h include/rpm/header.h \
	include/rpm/rpmdb.h include/rpm/rpmcallback.h \
	include/rpm/rpmcli.h include/rpm/rpmlib.h include/rpm/rpmds.h \
	include/rpm/rpmfi.h include/rpm/rpmfiles.h \
	include/rpm/rpmpol.h include/rpm/rpmps.h include/rpm/rpmprob.h \
	include/rpm/rpmtag.h include/rpm/rpmtd.h include/rpm/rpmte.h \
	include/rpm/rpmts.h include/rpm/rpmtypes.h include/rpm/rpmvf.h \
	include/rpm/rpmarchive.h include/rpm/rpmsign.h \
	include/rpm/rpmbuild.h include/rpm/rpmfc.h \
	include/rpm/rpmspec.h
SUBDIRS = po misc $(am__append_1) $(am__append_2) rpmio lib sign build \
	scripts fileattrs doc . $(am__append_3) $(am__append_4) \
	$(am__append_5)
DIST_SUBDIRS = po misc luaext rpmio lib sign build python scripts fileattrs doc tests plugins
pkgconfigdir = $(libdir)/pkgconfig
AM_CPPFLAGS = -I$(top_builddir) -I$(top_srcdir) \
	-I$(top_builddir)/include/ -I$(top_srcdir)/build \
	-I$(top_srcdir)/lib -I$(top_srcdir)/rpmio \
	  \
	  \
	-I$(top_srcdir)/misc -DLOCALEDIR="\"$(localedir)\"" \
	-DLIBRPMALIAS_FILENAME="\"rpmpopt-${VERSION}\""
pkginclude_HEADERS = rpmio/argv.h rpmio/rpmio.h rpmio/rpmurl.h \
	rpmio/rpmmacro.h rpmio/rpmlog.h rpmio/rpmpgp.h rpmio/rpmsq.h \
	rpmio/rpmstring.h rpmio/rpmstrpool.h rpmio/rpmsw.h \
	rpmio/rpmfileutil.h rpmio/rpmutil.h rpmio/rpmkeyring.h \
	rpmio/rpmbase64.h lib/header.h lib/rpmdb.h lib/rpmcallback.h \
	lib/rpmcli.h lib/rpmlib.h lib/rpmds.h lib/rpmfi.h \
	lib/rpmfiles.h lib/rpmpol.h lib/rpmps.h lib/rpmprob.h \
	lib/rpmtag.h lib/rpmtd.h lib/rpmte.h lib/rpmts.h \
	lib/rpmtypes.h lib/rpmvf.h lib/rpmarchive.h sign/rpmsign.h \
	build/rpmbuild.h build/rpmfc.h build/rpmspec.h
nodist_pkginclude_HEADERS = 
rpmconfig_SCRIPTS = mkinstalldirs config.guess config.sub \
	$(am__append_7)
noinst_LTLIBRARIES = libcliutils.la
libcliutils_la_SOURCES = cliutils.h cliutils.c
libcliutils_la_CPPFLAGS = $(AM_CPPFLAGS)
libcliutils_la_LIBADD = lib/librpm.la rpmio/librpmio.la \
	/usr/lib64/libpopt.a $(am__empty)
rpm_SOURCES = rpmqv.c debug.h system.h
rpm_CPPFLAGS = $(AM_CPPFLAGS) -DIAM_RPMEIU -DIAM_RPMQ -DIAM_RPMV
rpm_LDADD = libcliutils.la lib/librpm.la rpmio/librpmio.la \
	/usr/lib64/libpopt.a $(am__empty)
rpmdb_SOURCES = rpmdb.c debug.h system.h
rpmdb_CPPFLAGS = $(AM_CPPFLAGS)
rpmdb_LDADD = libcliutils.la lib/librpm.la rpmio/librpmio.la \
	/usr/lib64/libpopt.a $(am__empty)
rpmkeys_SOURCES = rpmkeys.c debug.h system.h
rpmkeys_CPPFLAGS = $(AM_CPPFLAGS)
rpmkeys_LDADD = libcliutils.la lib/librpm.la rpmio/librpmio.la \
	/usr/lib64/libpopt.a $(am__empty)
rpmsign_SOURCES = rpmsign.c debug.h system.h
rpmsign_CPPFLAGS = $(AM_CPPFLAGS)
rpmsign_LDADD = libcliutils.la sign/librpmsign.la lib/librpm.la \
	rpmio/librpmio.la /usr/lib64/libpopt.a
rpmbuild_SOURCES = rpmbuild.c debug.h system.h
rpmbuild_CPPFLAGS = $(AM_CPPFLAGS)
rpmbuild_LDADD = libcliutils.la build/librpmbuild.la lib/librpm.la \
	rpmio/librpmio.la /usr/lib64/libpopt.a
rpmspec_SOURCES = rpmspec.c debug.h system.h
rpmspec_CPPFLAGS = $(AM_CPPFLAGS)
rpmspec_LDADD = libcliutils.la build/librpmbuild.la lib/librpm.la \
	rpmio/librpmio.la /usr/lib64/libpopt.a
rpm2cpio_SOURCES = rpm2cpio.c debug.h system.h
rpm2cpio_LDADD = lib/librpm.la rpmio/librpmio.la /usr/lib64/libpopt.a
rpm2archive_SOURCES = rpm2archive.c debug.h system.h
rpm2archive_LDADD = lib/librpm.la rpmio/librpmio.la /usr/lib64/libpopt.a \
	-larchive $(am__empty)
debugedit_SOURCES = tools/debugedit.c tools/hashtab.c tools/hashtab.h
debugedit_LDADD =  \
	rpmio/librpmio.la \
	-lelf \
	/usr/lib64/libpopt.a \
	$(am__append_9) \
	$(am__append_10)
elfdeps_SOURCES = tools/elfdeps.c
elfdeps_LDADD = rpmio/librpmio.la lib/librpm.la \
	-lelf /usr/lib64/libpopt.a $(am__empty)
sepdebugcrcfix_SOURCES = tools/sepdebugcrcfix.c
sepdebugcrcfix_LDADD = -lelf
rpmdeps_SOURCES = tools/rpmdeps.c
rpmdeps_LDADD = lib/librpm.la rpmio/librpmio.la build/librpmbuild.la /usr/lib64/libpopt.a
rpmgraph_SOURCES = tools/rpmgraph.c
rpmgraph_LDADD = lib/librpm.la rpmio/librpmio.la /usr/lib64/libpopt.a
dist_bin_SCRIPTS = scripts/gendiff
rpmconfig_DATA = rpmrc rpmpopt-$(VERSION)
noinst_DATA = macros platform $(am__append_12) $(am__append_13)
pkgconfig_DATA = rpm.pc
usrsrcdir = $(prefix)/src
rpmvardir = $(localstatedir)/lib/rpm
rpmvar_DATA = 
MAINTAINERCLEANFILES = ChangeLog
DISTCLEANFILES = db.h
all: $(BUILT_SOURCES) config.h
	$(MAKE) $(AM_MAKEFLAGS) all-recursive

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am $(top_srcdir)/rpm.am $(top_srcdir)/preinstall.am $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles);; \
	esac;
$(top_srcdir)/rpm.am $(top_srcdir)/preinstall.am $(am__empty):

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@test -f $@ || rm -f stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) stamp-h1

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	 || test -f $$p1 \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list
install-rpmlibexecPROGRAMS: $(rpmlibexec_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(rpmlibexec_PROGRAMS)'; test -n "$(rpmlibexecdir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(rpmlibexecdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(rpmlibexecdir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	 || test -f $$p1 \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(rpmlibexecdir)$$dir'"; \
	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(rpmlibexecdir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-rpmlibexecPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(rpmlibexec_PROGRAMS)'; test -n "$(rpmlibexecdir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(rpmlibexecdir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(rpmlibexecdir)" && rm -f $$files

clean-rpmlibexecPROGRAMS:
	@list='$(rpmlibexec_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list

clean-noinstLTLIBRARIES:
	-test -z "$(noinst_LTLIBRARIES)" || rm -f $(noinst_LTLIBRARIES)
	@list='$(noinst_LTLIBRARIES)'; \
	locs=`for p in $$list; do echo $$p; done | \
	      sed 's|^[^/]*$$|.|; s|/[^/]*$$||; s|$$|/so_locations|' | \
	      sort -u`; \
	test -z "$$locs" || { \
	  echo rm -f $${locs}; \
	  rm -f $${locs}; \
	}

libcliutils.la: $(libcliutils_la_OBJECTS) $(libcliutils_la_DEPENDENCIES) $(EXTRA_libcliutils_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(LINK)  $(libcliutils_la_OBJECTS) $(libcliutils_la_LIBADD) $(LIBS)
tools/$(am__dirstamp):
	@$(MKDIR_P) tools
	@: > tools/$(am__dirstamp)
tools/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) tools/$(DEPDIR)
	@: > tools/$(DEPDIR)/$(am__dirstamp)
tools/debugedit.$(OBJEXT): tools/$(am__dirstamp) \
	tools/$(DEPDIR)/$(am__dirstamp)
tools/hashtab.$(OBJEXT): tools/$(am__dirstamp) \
	tools/$(DEPDIR)/$(am__dirstamp)

debugedit$(EXEEXT): $(debugedit_OBJECTS) $(debugedit_DEPENDENCIES) $(EXTRA_debugedit_DEPENDENCIES) 
	@rm -f debugedit$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(debugedit_OBJECTS) $(debugedit_LDADD) $(LIBS)
tools/elfdeps.$(OBJEXT): tools/$(am__dirstamp) \
	tools/$(DEPDIR)/$(am__dirstamp)

elfdeps$(EXEEXT): $(elfdeps_OBJECTS) $(elfdeps_DEPENDENCIES) $(EXTRA_elfdeps_DEPENDENCIES) 
	@rm -f elfdeps$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(elfdeps_OBJECTS) $(elfdeps_LDADD) $(LIBS)

rpm$(EXEEXT): $(rpm_OBJECTS) $(rpm_DEPENDENCIES) $(EXTRA_rpm_DEPENDENCIES) 
	@rm -f rpm$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(rpm_OBJECTS) $(rpm_LDADD) $(LIBS)

rpm2archive$(EXEEXT): $(rpm2archive_OBJECTS) $(rpm2archive_DEPENDENCIES) $(EXTRA_rpm2archive_DEPENDENCIES) 
	@rm -f rpm2archive$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(rpm2archive_OBJECTS) $(rpm2archive_LDADD) $(LIBS)

rpm2cpio$(EXEEXT): $(rpm2cpio_OBJECTS) $(rpm2cpio_DEPENDENCIES) $(EXTRA_rpm2cpio_DEPENDENCIES) 
	@rm -f rpm2cpio$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(rpm2cpio_OBJECTS) $(rpm2cpio_LDADD) $(LIBS)

rpmbuild$(EXEEXT): $(rpmbuild_OBJECTS) $(rpmbuild_DEPENDENCIES) $(EXTRA_rpmbuild_DEPENDENCIES) 
	@rm -f rpmbuild$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(rpmbuild_OBJECTS) $(rpmbuild_LDADD) $(LIBS)

rpmdb$(EXEEXT): $(rpmdb_OBJECTS) $(rpmdb_DEPENDENCIES) $(EXTRA_rpmdb_DEPENDENCIES) 
	@rm -f rpmdb$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(rpmdb_OBJECTS) $(rpmdb_LDADD) $(LIBS)
tools/rpmdeps.$(OBJEXT): tools/$(am__dirstamp) \
	tools/$(DEPDIR)/$(am__dirstamp)

rpmdeps$(EXEEXT): $(rpmdeps_OBJECTS) $(rpmdeps_DEPENDENCIES) $(EXTRA_rpmdeps_DEPENDENCIES) 
	@rm -f rpmdeps$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(rpmdeps_OBJECTS) $(rpmdeps_LDADD) $(LIBS)
tools/rpmgraph.$(OBJEXT): tools/$(am__dirstamp) \
	tools/$(DEPDIR)/$(am__dirstamp)

rpmgraph$(EXEEXT): $(rpmgraph_OBJECTS) $(rpmgraph_DEPENDENCIES) $(EXTRA_rpmgraph_DEPENDENCIES) 
	@rm -f rpmgraph$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(rpmgraph_OBJECTS) $(rpmgraph_LDADD) $(LIBS)

rpmkeys$(EXEEXT): $(rpmkeys_OBJECTS) $(rpmkeys_DEPENDENCIES) $(EXTRA_rpmkeys_DEPENDENCIES) 
	@rm -f rpmkeys$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(rpmkeys_OBJECTS) $(rpmkeys_LDADD) $(LIBS)

rpmsign$(EXEEXT): $(rpmsign_OBJECTS) $(rpmsign_DEPENDENCIES) $(EXTRA_rpmsign_DEPENDENCIES) 
	@rm -f rpmsign$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(rpmsign_OBJECTS) $(rpmsign_LDADD) $(LIBS)

rpmspec$(EXEEXT): $(rpmspec_OBJECTS) $(rpmspec_DEPENDENCIES) $(EXTRA_rpmspec_DEPENDENCIES) 
	@rm -f rpmspec$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(rpmspec_OBJECTS) $(rpmspec_LDADD) $(LIBS)
tools/sepdebugcrcfix.$(OBJEXT): tools/$(am__dirstamp) \
	tools/$(DEPDIR)/$(am__dirstamp)

sepdebugcrcfix$(EXEEXT): $(sepdebugcrcfix_OBJECTS) $(sepdebugcrcfix_DEPENDENCIES) $(EXTRA_sepdebugcrcfix_DEPENDENCIES) 
	@rm -f sepdebugcrcfix$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(sepdebugcrcfix_OBJECTS) $(sepdebugcrcfix_LDADD) $(LIBS)
install-dist_binSCRIPTS: $(dist_bin_SCRIPTS)
	@$(NORMAL_INSTALL)
	@list='$(dist_bin_SCRIPTS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  if test -f "$$d$$p"; then echo "$$d$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n' \
	    -e 'h;s|.*|.|' \
	    -e 'p;x;s,.*/,,;$(transform)' | sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1; } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) { files[d] = files[d] " " $$1; \
	      if (++n[d] == $(am__install_max)) { \
		print "f", d, files[d]; n[d] = 0; files[d] = "" } } \
	    else { print "f", d "/" $$4, $$1 } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	     if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	     test -z "$$files" || { \
	       echo " $(INSTALL_SCRIPT) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	       $(INSTALL_SCRIPT) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	     } \
	; done

uninstall-dist_binSCRIPTS:
	@$(NORMAL_UNINSTALL)
	@list='$(dist_bin_SCRIPTS)'; test -n "$(bindir)" || exit 0; \
	files=`for p in $$list; do echo "$$p"; done | \
	       sed -e 's,.*/,,;$(transform)'`; \
	dir='$(DESTDIR)$(bindir)'; $(am__uninstall_files_from_dir)
install-rpmconfigSCRIPTS: $(rpmconfig_SCRIPTS)
	@$(NORMAL_INSTALL)
	@list='$(rpmconfig_SCRIPTS)'; test -n "$(rpmconfigdir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(rpmconfigdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(rpmconfigdir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  if test -f "$$d$$p"; then echo "$$d$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n' \
	    -e 'h;s|.*|.|' \
	    -e 'p;x;s,.*/,,;$(transform)' | sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1; } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) { files[d] = files[d] " " $$1; \
	      if (++n[d] == $(am__install_max)) { \
		print "f", d, files[d]; n[d] = 0; files[d] = "" } } \
	    else { print "f", d "/" $$4, $$1 } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	     if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	     test -z "$$files" || { \
	       echo " $(INSTALL_SCRIPT) $$files '$(DESTDIR)$(rpmconfigdir)$$dir'"; \
	       $(INSTALL_SCRIPT) $$files "$(DESTDIR)$(rpmconfigdir)$$dir" || exit $$?; \
	     } \
	; done

uninstall-rpmconfigSCRIPTS:
	@$(NORMAL_UNINSTALL)
	@list='$(rpmconfig_SCRIPTS)'; test -n "$(rpmconfigdir)" || exit 0; \
	files=`for p in $$list; do echo "$$p"; done | \
	       sed -e 's,.*/,,;$(transform)'`; \
	dir='$(DESTDIR)$(rpmconfigdir)'; $(am__uninstall_files_from_dir)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f tools/*.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/libcliutils_la-cliutils.Plo # am--include-marker
include ./$(DEPDIR)/rpm-rpmqv.Po # am--include-marker
include ./$(DEPDIR)/rpm2archive.Po # am--include-marker
include ./$(DEPDIR)/rpm2cpio.Po # am--include-marker
include ./$(DEPDIR)/rpmbuild-rpmbuild.Po # am--include-marker
include ./$(DEPDIR)/rpmdb-rpmdb.Po # am--include-marker
include ./$(DEPDIR)/rpmkeys-rpmkeys.Po # am--include-marker
include ./$(DEPDIR)/rpmsign-rpmsign.Po # am--include-marker
include ./$(DEPDIR)/rpmspec-rpmspec.Po # am--include-marker
include tools/$(DEPDIR)/debugedit.Po # am--include-marker
include tools/$(DEPDIR)/elfdeps.Po # am--include-marker
include tools/$(DEPDIR)/hashtab.Po # am--include-marker
include tools/$(DEPDIR)/rpmdeps.Po # am--include-marker
include tools/$(DEPDIR)/rpmgraph.Po # am--include-marker
include tools/$(DEPDIR)/sepdebugcrcfix.Po # am--include-marker

$(am__depfiles_remade):
	@$(MKDIR_P) $(@D)
	@echo '# dummy' >$@-t && $(am__mv) $@-t $@

am--depfiles: $(am__depfiles_remade)

.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.c.lo:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	$(AM_V_CC)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LTCOMPILE) -c -o $@ $<

libcliutils_la-cliutils.lo: cliutils.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcliutils_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libcliutils_la-cliutils.lo -MD -MP -MF $(DEPDIR)/libcliutils_la-cliutils.Tpo -c -o libcliutils_la-cliutils.lo `test -f 'cliutils.c' || echo '$(srcdir)/'`cliutils.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/libcliutils_la-cliutils.Tpo $(DEPDIR)/libcliutils_la-cliutils.Plo
#	$(AM_V_CC)source='cliutils.c' object='libcliutils_la-cliutils.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcliutils_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libcliutils_la-cliutils.lo `test -f 'cliutils.c' || echo '$(srcdir)/'`cliutils.c

rpm-rpmqv.o: rpmqv.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(rpm_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT rpm-rpmqv.o -MD -MP -MF $(DEPDIR)/rpm-rpmqv.Tpo -c -o rpm-rpmqv.o `test -f 'rpmqv.c' || echo '$(srcdir)/'`rpmqv.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpm-rpmqv.Tpo $(DEPDIR)/rpm-rpmqv.Po
#	$(AM_V_CC)source='rpmqv.c' object='rpm-rpmqv.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(rpm_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o rpm-rpmqv.o `test -f 'rpmqv.c' || echo '$(srcdir)/'`rpmqv.c

rpm-rpmqv.obj: rpmqv.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(rpm_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT rpm-rpmqv.obj -MD -MP -MF $(DEPDIR)/rpm-rpmqv.Tpo -c -o rpm-rpmqv.obj `if test -f 'rpmqv.c'; then $(CYGPATH_W) 'rpmqv.c'; else $(CYGPATH_W) '$(srcdir)/rpmqv.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpm-rpmqv.Tpo $(DEPDIR)/rpm-rpmqv.Po
#	$(AM_V_CC)source='rpmqv.c' object='rpm-rpmqv.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(rpm_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o rpm-rpmqv.obj `if test -f 'rpmqv.c'; then $(CYGPATH_W) 'rpmqv.c'; else $(CYGPATH_W) '$(srcdir)/rpmqv.c'; fi`

rpmbuild-rpmbuild.o: rpmbuild.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(rpmbuild_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT rpmbuild-rpmbuild.o -MD -MP -MF $(DEPDIR)/rpmbuild-rpmbuild.Tpo -c -o rpmbuild-rpmbuild.o `test -f 'rpmbuild.c' || echo '$(srcdir)/'`rpmbuild.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpmbuild-rpmbuild.Tpo $(DEPDIR)/rpmbuild-rpmbuild.Po
#	$(AM_V_CC)source='rpmbuild.c' object='rpmbuild-rpmbuild.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(rpmbuild_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o rpmbuild-rpmbuild.o `test -f 'rpmbuild.c' || echo '$(srcdir)/'`rpmbuild.c

rpmbuild-rpmbuild.obj: rpmbuild.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(rpmbuild_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT rpmbuild-rpmbuild.obj -MD -MP -MF $(DEPDIR)/rpmbuild-rpmbuild.Tpo -c -o rpmbuild-rpmbuild.obj `if test -f 'rpmbuild.c'; then $(CYGPATH_W) 'rpmbuild.c'; else $(CYGPATH_W) '$(srcdir)/rpmbuild.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpmbuild-rpmbuild.Tpo $(DEPDIR)/rpmbuild-rpmbuild.Po
#	$(AM_V_CC)source='rpmbuild.c' object='rpmbuild-rpmbuild.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(rpmbuild_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o rpmbuild-rpmbuild.obj `if test -f 'rpmbuild.c'; then $(CYGPATH_W) 'rpmbuild.c'; else $(CYGPATH_W) '$(srcdir)/rpmbuild.c'; fi`

rpmdb-rpmdb.o: rpmdb.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(rpmdb_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT rpmdb-rpmdb.o -MD -MP -MF $(DEPDIR)/rpmdb-rpmdb.Tpo -c -o rpmdb-rpmdb.o `test -f 'rpmdb.c' || echo '$(srcdir)/'`rpmdb.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpmdb-rpmdb.Tpo $(DEPDIR)/rpmdb-rpmdb.Po
#	$(AM_V_CC)source='rpmdb.c' object='rpmdb-rpmdb.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(rpmdb_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o rpmdb-rpmdb.o `test -f 'rpmdb.c' || echo '$(srcdir)/'`rpmdb.c

rpmdb-rpmdb.obj: rpmdb.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(rpmdb_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT rpmdb-rpmdb.obj -MD -MP -MF $(DEPDIR)/rpmdb-rpmdb.Tpo -c -o rpmdb-rpmdb.obj `if test -f 'rpmdb.c'; then $(CYGPATH_W) 'rpmdb.c'; else $(CYGPATH_W) '$(srcdir)/rpmdb.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpmdb-rpmdb.Tpo $(DEPDIR)/rpmdb-rpmdb.Po
#	$(AM_V_CC)source='rpmdb.c' object='rpmdb-rpmdb.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(rpmdb_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o rpmdb-rpmdb.obj `if test -f 'rpmdb.c'; then $(CYGPATH_W) 'rpmdb.c'; else $(CYGPATH_W) '$(srcdir)/rpmdb.c'; fi`

rpmkeys-rpmkeys.o: rpmkeys.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(rpmkeys_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT rpmkeys-rpmkeys.o -MD -MP -MF $(DEPDIR)/rpmkeys-rpmkeys.Tpo -c -o rpmkeys-rpmkeys.o `test -f 'rpmkeys.c' || echo '$(srcdir)/'`rpmkeys.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpmkeys-rpmkeys.Tpo $(DEPDIR)/rpmkeys-rpmkeys.Po
#	$(AM_V_CC)source='rpmkeys.c' object='rpmkeys-rpmkeys.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(rpmkeys_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o rpmkeys-rpmkeys.o `test -f 'rpmkeys.c' || echo '$(srcdir)/'`rpmkeys.c

rpmkeys-rpmkeys.obj: rpmkeys.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(rpmkeys_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT rpmkeys-rpmkeys.obj -MD -MP -MF $(DEPDIR)/rpmkeys-rpmkeys.Tpo -c -o rpmkeys-rpmkeys.obj `if test -f 'rpmkeys.c'; then $(CYGPATH_W) 'rpmkeys.c'; else $(CYGPATH_W) '$(srcdir)/rpmkeys.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpmkeys-rpmkeys.Tpo $(DEPDIR)/rpmkeys-rpmkeys.Po
#	$(AM_V_CC)source='rpmkeys.c' object='rpmkeys-rpmkeys.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(rpmkeys_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o rpmkeys-rpmkeys.obj `if test -f 'rpmkeys.c'; then $(CYGPATH_W) 'rpmkeys.c'; else $(CYGPATH_W) '$(srcdir)/rpmkeys.c'; fi`

rpmsign-rpmsign.o: rpmsign.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(rpmsign_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT rpmsign-rpmsign.o -MD -MP -MF $(DEPDIR)/rpmsign-rpmsign.Tpo -c -o rpmsign-rpmsign.o `test -f 'rpmsign.c' || echo '$(srcdir)/'`rpmsign.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpmsign-rpmsign.Tpo $(DEPDIR)/rpmsign-rpmsign.Po
#	$(AM_V_CC)source='rpmsign.c' object='rpmsign-rpmsign.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(rpmsign_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o rpmsign-rpmsign.o `test -f 'rpmsign.c' || echo '$(srcdir)/'`rpmsign.c

rpmsign-rpmsign.obj: rpmsign.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(rpmsign_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT rpmsign-rpmsign.obj -MD -MP -MF $(DEPDIR)/rpmsign-rpmsign.Tpo -c -o rpmsign-rpmsign.obj `if test -f 'rpmsign.c'; then $(CYGPATH_W) 'rpmsign.c'; else $(CYGPATH_W) '$(srcdir)/rpmsign.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpmsign-rpmsign.Tpo $(DEPDIR)/rpmsign-rpmsign.Po
#	$(AM_V_CC)source='rpmsign.c' object='rpmsign-rpmsign.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(rpmsign_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o rpmsign-rpmsign.obj `if test -f 'rpmsign.c'; then $(CYGPATH_W) 'rpmsign.c'; else $(CYGPATH_W) '$(srcdir)/rpmsign.c'; fi`

rpmspec-rpmspec.o: rpmspec.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(rpmspec_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT rpmspec-rpmspec.o -MD -MP -MF $(DEPDIR)/rpmspec-rpmspec.Tpo -c -o rpmspec-rpmspec.o `test -f 'rpmspec.c' || echo '$(srcdir)/'`rpmspec.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpmspec-rpmspec.Tpo $(DEPDIR)/rpmspec-rpmspec.Po
#	$(AM_V_CC)source='rpmspec.c' object='rpmspec-rpmspec.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(rpmspec_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o rpmspec-rpmspec.o `test -f 'rpmspec.c' || echo '$(srcdir)/'`rpmspec.c

rpmspec-rpmspec.obj: rpmspec.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(rpmspec_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT rpmspec-rpmspec.obj -MD -MP -MF $(DEPDIR)/rpmspec-rpmspec.Tpo -c -o rpmspec-rpmspec.obj `if test -f 'rpmspec.c'; then $(CYGPATH_W) 'rpmspec.c'; else $(CYGPATH_W) '$(srcdir)/rpmspec.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/rpmspec-rpmspec.Tpo $(DEPDIR)/rpmspec-rpmspec.Po
#	$(AM_V_CC)source='rpmspec.c' object='rpmspec-rpmspec.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(rpmspec_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o rpmspec-rpmspec.obj `if test -f 'rpmspec.c'; then $(CYGPATH_W) 'rpmspec.c'; else $(CYGPATH_W) '$(srcdir)/rpmspec.c'; fi`

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool config.lt
install-pkgconfigDATA: $(pkgconfig_DATA)
	@$(NORMAL_INSTALL)
	@list='$(pkgconfig_DATA)'; test -n "$(pkgconfigdir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(pkgconfigdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(pkgconfigdir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(pkgconfigdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(pkgconfigdir)" || exit $$?; \
	done

uninstall-pkgconfigDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(pkgconfig_DATA)'; test -n "$(pkgconfigdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(pkgconfigdir)'; $(am__uninstall_files_from_dir)
install-rpmconfigDATA: $(rpmconfig_DATA)
	@$(NORMAL_INSTALL)
	@list='$(rpmconfig_DATA)'; test -n "$(rpmconfigdir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(rpmconfigdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(rpmconfigdir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(rpmconfigdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(rpmconfigdir)" || exit $$?; \
	done

uninstall-rpmconfigDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(rpmconfig_DATA)'; test -n "$(rpmconfigdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(rpmconfigdir)'; $(am__uninstall_files_from_dir)
install-rpmvarDATA: $(rpmvar_DATA)
	@$(NORMAL_INSTALL)
	@list='$(rpmvar_DATA)'; test -n "$(rpmvardir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(rpmvardir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(rpmvardir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(rpmvardir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(rpmvardir)" || exit $$?; \
	done

uninstall-rpmvarDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(rpmvar_DATA)'; test -n "$(rpmvardir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(rpmvardir)'; $(am__uninstall_files_from_dir)
install-nodist_pkgincludeHEADERS: $(nodist_pkginclude_HEADERS)
	@$(NORMAL_INSTALL)
	@list='$(nodist_pkginclude_HEADERS)'; test -n "$(pkgincludedir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(pkgincludedir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(pkgincludedir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_HEADER) $$files '$(DESTDIR)$(pkgincludedir)'"; \
	  $(INSTALL_HEADER) $$files "$(DESTDIR)$(pkgincludedir)" || exit $$?; \
	done

uninstall-nodist_pkgincludeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(nodist_pkginclude_HEADERS)'; test -n "$(pkgincludedir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(pkgincludedir)'; $(am__uninstall_files_from_dir)
install-pkgincludeHEADERS: $(pkginclude_HEADERS)
	@$(NORMAL_INSTALL)
	@list='$(pkginclude_HEADERS)'; test -n "$(pkgincludedir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(pkgincludedir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(pkgincludedir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_HEADER) $$files '$(DESTDIR)$(pkgincludedir)'"; \
	  $(INSTALL_HEADER) $$files "$(DESTDIR)$(pkgincludedir)" || exit $$?; \
	done

uninstall-pkgincludeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(pkginclude_HEADERS)'; test -n "$(pkgincludedir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(pkgincludedir)'; $(am__uninstall_files_from_dir)

# This directory's subdirectories are mostly independent; you can cd
# into them and run 'make' without going through this Makefile.
# To change the values of 'make' variables: instead of editing Makefiles,
# (1) if the variable is set in 'config.status', edit 'config.status'
#     (which will cause the Makefiles to be regenerated when you run 'make');
# (2) otherwise, pass the desired values on the 'make' command line.
$(am__recursive_targets):
	@fail=; \
	if $(am__make_keepgoing); then \
	  failcom='fail=yes'; \
	else \
	  failcom='exit 1'; \
	fi; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-recursive
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      set "$$@" "$$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-recursive

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-recursive

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) distdir-am

distdir-am: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    $(am__make_dryrun) \
	      || test -d "$(distdir)/$$subdir" \
	      || $(MKDIR_P) "$(distdir)/$$subdir" \
	      || exit 1; \
	    dir1=$$subdir; dir2="$(distdir)/$$subdir"; \
	    $(am__relativize); \
	    new_distdir=$$reldir; \
	    dir1=$$subdir; dir2="$(top_distdir)"; \
	    $(am__relativize); \
	    new_top_distdir=$$reldir; \
	    echo " (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir="$$new_top_distdir" distdir="$$new_distdir" \\"; \
	    echo "     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)"; \
	    ($(am__cd) $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$new_top_distdir" \
	        distdir="$$new_distdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
		am__skip_mode_fix=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	$(MAKE) $(AM_MAKEFLAGS) \
	  top_distdir="$(top_distdir)" distdir="$(distdir)" \
	  dist-hook
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).tar.gz
	$(am__post_remove_distdir)
dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-zstd: distdir
	tardir=$(distdir) && $(am__tar) | zstd -c $${ZSTD_CLEVEL-$${ZSTD_OPT--19}} >$(distdir).tar.zst
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	*.tar.zst*) \
	  zstd -dc $(distdir).tar.zst | $(am__untar) ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) $(AM_DISTCHECK_DVI_TARGET) \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) check-recursive
all-am: Makefile $(PROGRAMS) $(LTLIBRARIES) $(SCRIPTS) $(DATA) \
		$(HEADERS) config.h
installdirs: installdirs-recursive
installdirs-am:
	for dir in "$(DESTDIR)$(bindir)" "$(DESTDIR)$(rpmlibexecdir)" "$(DESTDIR)$(bindir)" "$(DESTDIR)$(rpmconfigdir)" "$(DESTDIR)$(pkgconfigdir)" "$(DESTDIR)$(rpmconfigdir)" "$(DESTDIR)$(rpmvardir)" "$(DESTDIR)$(pkgincludedir)" "$(DESTDIR)$(pkgincludedir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) install-recursive
install-exec: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f tools/$(DEPDIR)/$(am__dirstamp)
	-rm -f tools/$(am__dirstamp)
	-test -z "$(DISTCLEANFILES)" || rm -f $(DISTCLEANFILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-test -z "$(BUILT_SOURCES)" || rm -f $(BUILT_SOURCES)
	-test -z "$(MAINTAINERCLEANFILES)" || rm -f $(MAINTAINERCLEANFILES)
clean: clean-recursive

clean-am: clean-binPROGRAMS clean-generic clean-libtool clean-local \
	clean-noinstLTLIBRARIES clean-rpmlibexecPROGRAMS \
	mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
		-rm -f ./$(DEPDIR)/libcliutils_la-cliutils.Plo
	-rm -f ./$(DEPDIR)/rpm-rpmqv.Po
	-rm -f ./$(DEPDIR)/rpm2archive.Po
	-rm -f ./$(DEPDIR)/rpm2cpio.Po
	-rm -f ./$(DEPDIR)/rpmbuild-rpmbuild.Po
	-rm -f ./$(DEPDIR)/rpmdb-rpmdb.Po
	-rm -f ./$(DEPDIR)/rpmkeys-rpmkeys.Po
	-rm -f ./$(DEPDIR)/rpmsign-rpmsign.Po
	-rm -f ./$(DEPDIR)/rpmspec-rpmspec.Po
	-rm -f tools/$(DEPDIR)/debugedit.Po
	-rm -f tools/$(DEPDIR)/elfdeps.Po
	-rm -f tools/$(DEPDIR)/hashtab.Po
	-rm -f tools/$(DEPDIR)/rpmdeps.Po
	-rm -f tools/$(DEPDIR)/rpmgraph.Po
	-rm -f tools/$(DEPDIR)/sepdebugcrcfix.Po
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-local distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

html-am:

info: info-recursive

info-am:

install-data-am: install-data-local install-nodist_pkgincludeHEADERS \
	install-pkgconfigDATA install-pkgincludeHEADERS \
	install-rpmconfigDATA install-rpmconfigSCRIPTS \
	install-rpmvarDATA

install-dvi: install-dvi-recursive

install-dvi-am:

install-exec-am: install-binPROGRAMS install-dist_binSCRIPTS \
	install-rpmlibexecPROGRAMS
	@$(NORMAL_INSTALL)
	$(MAKE) $(AM_MAKEFLAGS) install-exec-hook
install-html: install-html-recursive

install-html-am:

install-info: install-info-recursive

install-info-am:

install-man:

install-pdf: install-pdf-recursive

install-pdf-am:

install-ps: install-ps-recursive

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
		-rm -f ./$(DEPDIR)/libcliutils_la-cliutils.Plo
	-rm -f ./$(DEPDIR)/rpm-rpmqv.Po
	-rm -f ./$(DEPDIR)/rpm2archive.Po
	-rm -f ./$(DEPDIR)/rpm2cpio.Po
	-rm -f ./$(DEPDIR)/rpmbuild-rpmbuild.Po
	-rm -f ./$(DEPDIR)/rpmdb-rpmdb.Po
	-rm -f ./$(DEPDIR)/rpmkeys-rpmkeys.Po
	-rm -f ./$(DEPDIR)/rpmsign-rpmsign.Po
	-rm -f ./$(DEPDIR)/rpmspec-rpmspec.Po
	-rm -f tools/$(DEPDIR)/debugedit.Po
	-rm -f tools/$(DEPDIR)/elfdeps.Po
	-rm -f tools/$(DEPDIR)/hashtab.Po
	-rm -f tools/$(DEPDIR)/rpmdeps.Po
	-rm -f tools/$(DEPDIR)/rpmgraph.Po
	-rm -f tools/$(DEPDIR)/sepdebugcrcfix.Po
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-dist_binSCRIPTS \
	uninstall-local uninstall-nodist_pkgincludeHEADERS \
	uninstall-pkgconfigDATA uninstall-pkgincludeHEADERS \
	uninstall-rpmconfigDATA uninstall-rpmconfigSCRIPTS \
	uninstall-rpmlibexecPROGRAMS uninstall-rpmvarDATA

.MAKE: $(am__recursive_targets) all check install install-am \
	install-exec install-exec-am install-strip

.PHONY: $(am__recursive_targets) CTAGS GTAGS TAGS all all-am \
	am--depfiles am--refresh check check-am clean \
	clean-binPROGRAMS clean-cscope clean-generic clean-libtool \
	clean-local clean-noinstLTLIBRARIES clean-rpmlibexecPROGRAMS \
	cscope cscopelist-am ctags ctags-am dist dist-all dist-bzip2 \
	dist-gzip dist-hook dist-lzip dist-shar dist-tarZ dist-xz \
	dist-zip dist-zstd distcheck distclean distclean-compile \
	distclean-generic distclean-hdr distclean-libtool \
	distclean-local distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-binPROGRAMS install-data \
	install-data-am install-data-local install-dist_binSCRIPTS \
	install-dvi install-dvi-am install-exec install-exec-am \
	install-exec-hook install-html install-html-am install-info \
	install-info-am install-man install-nodist_pkgincludeHEADERS \
	install-pdf install-pdf-am install-pkgconfigDATA \
	install-pkgincludeHEADERS install-ps install-ps-am \
	install-rpmconfigDATA install-rpmconfigSCRIPTS \
	install-rpmlibexecPROGRAMS install-rpmvarDATA install-strip \
	installcheck installcheck-am installdirs installdirs-am \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic mostlyclean-libtool \
	pdf pdf-am ps ps-am tags tags-am uninstall uninstall-am \
	uninstall-binPROGRAMS uninstall-dist_binSCRIPTS \
	uninstall-local uninstall-nodist_pkgincludeHEADERS \
	uninstall-pkgconfigDATA uninstall-pkgincludeHEADERS \
	uninstall-rpmconfigDATA uninstall-rpmconfigSCRIPTS \
	uninstall-rpmlibexecPROGRAMS uninstall-rpmvarDATA

.PRECIOUS: Makefile

rpmrc: $(top_srcdir)/rpmrc.in
	@$(SED) \
	  -e "s,[@]SYSCONFIGDIR[@],$(sysconfdir)/rpm,g" \
	  < $(top_srcdir)/rpmrc.in > rpmrc.tmp \
	  && ( cd $(top_builddir) && ./config.status --file=${subdir}/rpmrc:${subdir}/rpmrc.tmp )
macros: $(top_srcdir)/macros.in
	  ( cd $(top_builddir) && ./config.status --file=${subdir}/macros:${subdir}/macros.in )
platform: $(top_srcdir)/platform.in
	@$(SED) \
	  -e "s,[@]RPMCONFIGDIR[@],$(rpmconfigdir),g" \
	  < $(top_srcdir)/platform.in > platform.tmp \
	  && ( cd $(top_builddir) && ./config.status --file=${subdir}/platform:${subdir}/platform.tmp )
rpm.pc: $(top_srcdir)/rpm.pc.in
	@$(SED) \
	  -e "s,[@]RPMCONFIGDIR[@],$(rpmconfigdir),g" \
	  < $(top_srcdir)/rpm.pc.in > rpm.pc.tmp \
	  && ( cd $(top_builddir) && ./config.status --file=${subdir}/rpm.pc:${subdir}/rpm.pc.tmp )
rpmpopt-4.14.2.1: $(top_srcdir)/rpmpopt.in
	@$(SED) \
	  -e "s,[@]RPMCONFIGDIR[@],$(rpmconfigdir),g" \
	  -e "s,[@]BINDIR[@],$(bindir),g" \
	  < $(top_srcdir)/rpmpopt.in > rpmpopt-4.14.2.1.tmp \
	  && ( cd $(top_builddir) && ./config.status --file=${subdir}/rpmpopt-4.14.2.1:${subdir}/rpmpopt-4.14.2.1.tmp )

install-exec-hook:
	@rm -f $(DESTDIR)$(bindir)/rpmquery
	ln -s $(rpm_symlink_prefix)rpm $(DESTDIR)$(bindir)/rpmquery
	@rm -f $(DESTDIR)$(bindir)/rpmverify
	ln -s  $(rpm_symlink_prefix)rpm $(DESTDIR)$(bindir)/rpmverify

install-data-local:
	DESTDIR="$(DESTDIR)" pkglibdir="$(rpmconfigdir)" \
		$(SHELL) $(top_srcdir)/installplatform \
			rpmrc platform macros \
			$(RPMCANONVENDOR) $(RPMCANONOS) $(RPMCANONGNU)
	@$(MKDIR_P) $(DESTDIR)$(localstatedir)/tmp
	@$(MKDIR_P) $(DESTDIR)$(rpmconfigdir)/macros.d
	@$(MKDIR_P) $(DESTDIR)$(rpmconfigdir)/lua

# XXX to appease distcheck we need to remove "stuff" here...
uninstall-local:
	@rm -f $(DESTDIR)$(bindir)/rpmquery
	@rm -f $(DESTDIR)$(bindir)/rpmverify
	@rm -rf $(DESTDIR)$(rpmconfigdir)/platform/
	@rm -f $(DESTDIR)$(rpmconfigdir)/macros
	@rm -rf $(DESTDIR)$(rpmconfigdir)/macros.d
	@rm -rf $(DESTDIR)$(rpmconfigdir)/lua

# Build hacking docs only on request
#doc/hacking.doxy: doc/hacking.doxy.in doc/hacking/Doxyheader.h Makefile.am
#	$(SED) \
#	  -e "s,\@top_srcdir\@/,$(top_srcdir)/,g" \
#	  -e "s,[@]HAVE_DOT[@],$(HAVE_DOT)," \
#	  -e "s,[@]PACKAGE[@],$(PACKAGE)," \
#	  -e "s,[@]VERSION[@],$(VERSION)," \
#	< $(top_srcdir)/doc/hacking.doxy.in > doc/hacking.doxy

#doc/hacking/html/index.html: doc/hacking.doxy rpmpopt-4.14.2.1
#	/usr/bin/doxygen doc/hacking.doxy

# Always build librpm docs
doc/librpm.doxy: doc/librpm.doxy.in doc/librpm/Doxyheader.h Makefile.am configure.ac $(pkginclude_HEADERS)
	files=`echo " $(pkginclude_HEADERS)" | $(SED) -e "s, , \@top_srcdir\@/,g"`; \
	$(SED) -e "s,[@]pkginclude_HEADERS[@],$$files," \
	  -e "s,\@top_srcdir\@/,$(top_srcdir)/,g" \
	  -e "s,[@]HAVE_DOT[@],$(HAVE_DOT)," \
	  -e "s,[@]PACKAGE[@],$(PACKAGE)," \
	  -e "s,[@]VERSION[@],$(VERSION)," \
	< $(top_srcdir)/doc/librpm.doxy.in > doc/librpm.doxy

doc/librpm/html/index.html: doc/librpm.doxy
	/usr/bin/doxygen doc/librpm.doxy

#db.h:	$(top_builddir)/db3/db.h
#	$(LN_S) $(top_builddir)/db3/db.h $@

ChangeLog:
	touch ChangeLog

dist-hook:
	if [ -d .git ] && [ -x $(command -v git) ]; then git log --no-merges > $(distdir)/ChangeLog; fi

clean-local:
	rm -rf doc/hacking/html
	rm -rf include

distclean-local:
	rm -rf doc/librpm.doxy doc/librpm/html
	rm -rf Doxytags
	rm -f stamp-h.in db3/*.orig db3/db3lobjs

$(top_srcdir)/preinstall.am: Makefile.am
	rm -f $(top_srcdir)/preinstall.am
	@for f in $(HEADERS); do \
	  b=`basename $$f`; \
	  echo 'include/rpm/'$$b': '$$f' include/rpm/$$(dirstamp)' >> $(top_srcdir)/preinstall.am;\
	  echo '	$$(INSTALL_DATA) $$(top_srcdir)/'$$f' include/rpm/'$$b >> $(top_srcdir)/preinstall.am; \
	  echo 'BUILT_SOURCES += include/rpm/'$$b >> $(top_srcdir)/preinstall.am; \
	  echo 'CLEANFILES += include/rpm/'$$b  >> $(top_srcdir)/preinstall.am; \
	 done

include/rpm/$(dirstamp):
	@$(MKDIR_P) include/rpm
	@: > include/rpm/$(dirstamp)
include/rpm/argv.h: rpmio/argv.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/rpmio/argv.h include/rpm/argv.h
include/rpm/rpmio.h: rpmio/rpmio.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/rpmio/rpmio.h include/rpm/rpmio.h
include/rpm/rpmurl.h: rpmio/rpmurl.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/rpmio/rpmurl.h include/rpm/rpmurl.h
include/rpm/rpmmacro.h: rpmio/rpmmacro.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/rpmio/rpmmacro.h include/rpm/rpmmacro.h
include/rpm/rpmlog.h: rpmio/rpmlog.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/rpmio/rpmlog.h include/rpm/rpmlog.h
include/rpm/rpmpgp.h: rpmio/rpmpgp.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/rpmio/rpmpgp.h include/rpm/rpmpgp.h
include/rpm/rpmsq.h: rpmio/rpmsq.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/rpmio/rpmsq.h include/rpm/rpmsq.h
include/rpm/rpmstring.h: rpmio/rpmstring.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/rpmio/rpmstring.h include/rpm/rpmstring.h
include/rpm/rpmstrpool.h: rpmio/rpmstrpool.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/rpmio/rpmstrpool.h include/rpm/rpmstrpool.h
include/rpm/rpmsw.h: rpmio/rpmsw.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/rpmio/rpmsw.h include/rpm/rpmsw.h
include/rpm/rpmfileutil.h: rpmio/rpmfileutil.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/rpmio/rpmfileutil.h include/rpm/rpmfileutil.h
include/rpm/rpmutil.h: rpmio/rpmutil.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/rpmio/rpmutil.h include/rpm/rpmutil.h
include/rpm/rpmkeyring.h: rpmio/rpmkeyring.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/rpmio/rpmkeyring.h include/rpm/rpmkeyring.h
include/rpm/rpmbase64.h: rpmio/rpmbase64.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/rpmio/rpmbase64.h include/rpm/rpmbase64.h
include/rpm/header.h: lib/header.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/lib/header.h include/rpm/header.h
include/rpm/rpmdb.h: lib/rpmdb.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/lib/rpmdb.h include/rpm/rpmdb.h
include/rpm/rpmcallback.h: lib/rpmcallback.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/lib/rpmcallback.h include/rpm/rpmcallback.h
include/rpm/rpmcli.h: lib/rpmcli.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/lib/rpmcli.h include/rpm/rpmcli.h
include/rpm/rpmlib.h: lib/rpmlib.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/lib/rpmlib.h include/rpm/rpmlib.h
include/rpm/rpmds.h: lib/rpmds.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/lib/rpmds.h include/rpm/rpmds.h
include/rpm/rpmfi.h: lib/rpmfi.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/lib/rpmfi.h include/rpm/rpmfi.h
include/rpm/rpmfiles.h: lib/rpmfiles.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/lib/rpmfiles.h include/rpm/rpmfiles.h
include/rpm/rpmpol.h: lib/rpmpol.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/lib/rpmpol.h include/rpm/rpmpol.h
include/rpm/rpmps.h: lib/rpmps.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/lib/rpmps.h include/rpm/rpmps.h
include/rpm/rpmprob.h: lib/rpmprob.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/lib/rpmprob.h include/rpm/rpmprob.h
include/rpm/rpmtag.h: lib/rpmtag.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/lib/rpmtag.h include/rpm/rpmtag.h
include/rpm/rpmtd.h: lib/rpmtd.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/lib/rpmtd.h include/rpm/rpmtd.h
include/rpm/rpmte.h: lib/rpmte.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/lib/rpmte.h include/rpm/rpmte.h
include/rpm/rpmts.h: lib/rpmts.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/lib/rpmts.h include/rpm/rpmts.h
include/rpm/rpmtypes.h: lib/rpmtypes.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/lib/rpmtypes.h include/rpm/rpmtypes.h
include/rpm/rpmvf.h: lib/rpmvf.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/lib/rpmvf.h include/rpm/rpmvf.h
include/rpm/rpmarchive.h: lib/rpmarchive.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/lib/rpmarchive.h include/rpm/rpmarchive.h
include/rpm/rpmsign.h: sign/rpmsign.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/sign/rpmsign.h include/rpm/rpmsign.h
include/rpm/rpmbuild.h: build/rpmbuild.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/build/rpmbuild.h include/rpm/rpmbuild.h
include/rpm/rpmfc.h: build/rpmfc.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/build/rpmfc.h include/rpm/rpmfc.h
include/rpm/rpmspec.h: build/rpmspec.h include/rpm/$(dirstamp)
	$(INSTALL_DATA) $(top_srcdir)/build/rpmspec.h include/rpm/rpmspec.h

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
